---
- name: Disable cert checking in python
  ini_file:
    path: /etc/python/cert-verification.cfg
    section: https
    option: verify
    value: disable

- name: Ensure SystemID has same username as play
  xml:
    backup: yes
    path: /etc/sysconfig/rhn/systemid
    xpath: //member[name='username']/value/string
    value: "{{ rhn_username }}"

- name: Unregister from RHN
  rhn_register:
    state: absent
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"

- name: Register with needed channels
  rhn_register:
    state: present
    username: "{{ rhn_username }}" 
    password: "{{ rhn_password }}"
    channels: "{{ rhn_channels }}"  
    profilename: "{{ rhn_profilename | d (ansible_fqdn) }}"

- name: Re-enable cert checking in python
  ini_file:
    path: /etc/python/cert-verification.cfg
    section: https
    option: verify
    value: platform_default
